sudo: required
services:
  - docker

before_install:
  - docker build -t mfarhan0304/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mfarhan0304/react-test npm test -- --coverage

after_success:
  - docker build -t mfarhan0304/multi-client -f ./client
  - docker build -t mfarhan0304/multi-nginx -f ./nginx
  - docker build -t mfarhan0304/multi-server -f ./server
  - docker build -t mfarhan0304/multi-worker -f ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hubb
  - docker push mfarhan0304/multi-client
  - docker push mfarhan0304/multi-nginx
  - docker push mfarhan0304/multi-server
  - docker push mfarhan0304/multi-worker
